# config/protocols.yaml
http_server:
  enabled: true
  host: "127.0.0.1"
  port: 8000
  api_key: "your_http_api_key"
  cors_origins: ["http://localhost:3000"]

websocket_server:
  enabled: true
  host: "127.0.0.1"
  port: 8001
  auth_token: "your_websocket_auth_token"
  use_ssl: false

mqtt_server:
  enabled: false # Set to true if you want to test MQTT
  broker_address: "localhost"
  port: 1883

coap_server:
  enabled: false # Set to true if you want to test CoAP
  host: "127.0.0.1"
  port: 5683

upnp_server:
  enabled: true
  friendly_name: "PlaySEM Python Server"
  http_port: 8080

device_manager:
  broker_address: "mqtt://localhost:1883" # Example broker address for device manager